# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(blank=True, default='places/main_images/placeholder.jpg', null=True, upload_to='places/main_images', verbose_name='Main image')),
                ('title', models.CharField(max_length=256, verbose_name='Place title')),
                ('address', models.CharField(max_length=256, verbose_name='Place address')),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('budget', models.IntegerField(default=0)),
                ('style', models.IntegerField(default=0)),
                ('adventure', models.IntegerField(default=0)),
                ('landscape', models.IntegerField(default=0)),
                ('must_see', models.IntegerField(default=0)),
                ('energy', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0, verbose_name='Rating of a place')),
                ('positive_votes', models.IntegerField(default=0, verbose_name='Number of positive votes')),
                ('negative_votes', models.IntegerField(default=0, verbose_name='Number of negative votes')),
                ('categories', models.ManyToManyField(to='places.Category', verbose_name='Place categories')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places_images', verbose_name='Image for place')),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Place image',
                'verbose_name_plural': 'Place images',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Tag name')),
                ('rating', models.IntegerField(default=0, verbose_name='Tag rating')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='place', to='places.PlaceImage', verbose_name='Place images'),
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='place', to='places.Tag', verbose_name='Place tags'),
        ),
    ]
