# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, height_field=333, upload_to='users/profile_photos', verbose_name='Profile photo', width_field=333)),
                ('location', models.CharField(default='', max_length=64, verbose_name='User location')),
                ('status', models.CharField(default='User', max_length=64, verbose_name='User status')),
                ('followers', models.ManyToManyField(blank=True, related_name='_userprofile_followers_+', to='custom_auth_system.UserProfile', verbose_name='User followers')),
                ('following', models.ManyToManyField(blank=True, related_name='_userprofile_following_+', to='custom_auth_system.UserProfile', verbose_name='User following')),
                ('saved_places', models.ManyToManyField(blank=True, to='places.Place', verbose_name='Saved places')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User object')),
            ],
        ),
    ]
